### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by Akritic**

### CODE REVIEW

**Comment by motatoes** [comment]
digger plan

**Comment by Spartakovic** [comment]
digger plan

**Comment by Spartakovic** [comment]
digger plan

**Comment by Spartakovic** [comment]
digger plan

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-13 12:09:27 (UTC)</summary>
      <details><summary>Locking successful</summary>
  Project digger-tests/digger-demo-opa#prod has been locked by PR #17
</details>

<details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>


<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-13 21:38:35 (UTC)</summary>
  <details><summary>Unlocking successful</summary>
  Project unlocked (digger-tests/digger-demo-opa#prod).
</details>
</details>

**Pull request closed without merging**
