### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by Akritic**

### CODE REVIEW

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-18 23:10:52</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-18 23:16:52</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-18 23:18:54</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-19 14:09:11</summary>
    <details><summary>Locking successful</summary>
  Project digger-tests/digger-demo-opa#prod has been locked by PR #9
</details>

<details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-19 14:11:14</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-19 14:11:49</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-19 14:14:46</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=8078095421473472587]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-19 14:17:32</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-19 14:17:39</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-19 14:20:11</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-19 14:20:39</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=4617803969692202586]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-19 14:23:43</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=4311111463364827616]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-19 14:23:45</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-03 12:36:55 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger unlock. Check your policies
</details>
</details>

**Pull request closed without merging**
