### PR TITLE
Update project

### PR DESCRIPTION
**Pull request by ynden**

### CODE REVIEW

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 00:13:23 (UTC)</summary>
      <details><summary>Locking successful</summary>
  Project digger-tests/digger-demo-opa#prod has been locked by PR #21
</details>

<details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>


<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 00:16:59 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 00:23:23 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 00:25:36 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 00:28:39 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 00:29:45 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test: Creating...
null_resource.test: Creation complete after 0s [id=8489967007917076971]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 00:33:29 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 00:37:13 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 00:37:59 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 00:46:39 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 14:25:00 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger plan</b></summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies :x:
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 14:26:46 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 14:28:17 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger apply</b></summary>
  User Akritic is not allowed to perform action: digger apply. Check your policies :x:
</details>
</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 14:29:23 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test: Creating...
null_resource.test: Creation complete after 0s [id=8656051132257016998]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 14:51:59 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger plan</b></summary>
  User ynden is not allowed to perform action: digger plan. Check your policies :x:
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 14:56:04 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 14:57:06 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger apply</b></summary>
  User ynden is not allowed to perform action: digger apply. Check your policies :x:
</details>
</details>

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-19 14:59:42 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test: Creating...
null_resource.test: Creation complete after 0s [id=7553341371119290018]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 15:50:26 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger plan</b></summary>
  User motatoes is not allowed to perform action: digger plan. Check your policies :x:
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 16:21:00 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger plan</b></summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies :x:
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 16:22:53 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 16:23:46 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test: Creating...
null_resource.test: Creation complete after 0s [id=628904849257010628]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 16:24:46 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger plan</b></summary>
  User ynden is not allowed to perform action: digger plan. Check your policies :x:
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 16:25:15 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger plan</b></summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies :x:
</details>
</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 16:26:07 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger apply</b></summary>
  User Akritic is not allowed to perform action: digger apply. Check your policies :x:
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 16:26:51 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger plan</b></summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies :x:
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 16:32:17 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger plan</b></summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies :x:
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 17:13:38 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 17:13:43 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test: Creating...
null_resource.test: Creation complete after 0s [id=7218152573110837477]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 17:15:53 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger plan</b></summary>
  User ynden is not allowed to perform action: digger plan. Check your policies :x:
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 17:15:57 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger apply</b></summary>
  User ynden is not allowed to perform action: digger apply. Check your policies :x:
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 17:17:09 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 17:17:14 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test will be created
  + resource "null_resource" "test" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test: Creating...
null_resource.test: Creation complete after 0s [id=1566747274007972836]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-09-20 17:18:39 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger unlock</b></summary>
  User ynden is not allowed to perform action: digger unlock. Check your policies :x:
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Pull request closed without merging**
