### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by Akritic**

### CODE REVIEW

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-10-06 00:34:24 (UTC)</summary>
      <details><summary>Locking successful</summary>
  Project digger-tests/digger-demo-opa#prod has been locked by PR #24
</details>

<details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>


<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by Akritic** [comment]
digger plan

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-10-06 00:35:48 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger apply</b></summary>
  User Akritic is not allowed to perform action: digger apply. Check your policies :x:
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-10-06 00:38:17 (UTC)</summary>
        <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>


<details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>


<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-10-06 00:39:21 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-10-06 09:55:11 (UTC)</summary>
  <details><summary>Policy violation for <b>prod - digger unlock</b></summary>
  User motatoes is not allowed to perform action: digger unlock. Check your policies :x:
</details>
</details>

**Pull request closed without merging**
