### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by Akritic**

### CODE REVIEW

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-17 02:11:22</summary>
    <details><summary>Locking successful</summary>
  Project digger-tests/digger-demo-opa#prod has been locked by PR #8
</details>

<details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-17 02:14:10</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=2901536149171695932]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-17 02:17:37</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-17 02:20:28</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-17 02:22:21</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=6771080410190836015]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-17 02:24:41</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-17 14:35:15</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-18 10:52:40</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-18 11:03:22</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-18 11:17:58</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-18 11:39:44</summary>
  <details><summary>Policy violation</summary>
  User motatoes is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-18 12:01:05</summary>
  <details><summary>Policy violation</summary>
  User motatoes is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Pull request closed without merging**
