### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by Akritic**

### CODE REVIEW

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 23:55:06 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 23:58:09 (UTC)</summary>
      <details><summary>Locking successful</summary>
  Project digger-tests/digger-demo-opa#prod has been locked by PR #13
</details>

<details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>


<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-14 00:00:14 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-14 00:01:03 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=8725215938920331367]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-14 00:02:33 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-14 00:02:36 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=43566098493451877]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-14 00:04:10 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-14 00:05:43 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-14 00:06:32 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-14 00:07:14 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=8388023330709534793]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-18 00:20:10 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger unlock. Check your policies
</details>
</details>

**Pull request closed without merging**
