### PR TITLE
Change v0.1.30

### PR DESCRIPTION
**Pull request by ynden**

### CODE REVIEW

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 14:34:08 (UTC)</summary>
      <details><summary>Locking successful</summary>
  Project digger-tests/digger-demo-opa#prod has been locked by PR #12
</details>

<details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_1 will be created
  + resource "null_resource" "test_1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>


<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 14:35:17 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 14:36:39 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_1 will be created
  + resource "null_resource" "test_1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 14:37:26 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 14:38:24 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_1 will be created
  + resource "null_resource" "test_1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test_1: Creating...
null_resource.test_1: Creation complete after 0s [id=5435367614174525020]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 14:40:50 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_1 will be created
  + resource "null_resource" "test_1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test_1: Creating...
null_resource.test_1: Creation complete after 0s [id=6448844633198509781]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 14:40:52 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_1 will be created
  + resource "null_resource" "test_1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by ynden** [comment]
digger plan

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 14:47:18 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 14:47:21 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 14:48:37 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_1 will be created
  + resource "null_resource" "test_1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 14:48:36 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_1 will be created
  + resource "null_resource" "test_1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test_1: Creating...
null_resource.test_1: Creation complete after 0s [id=7287991321798962688]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 14:50:09 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger unlock. Check your policies
</details>
</details>

**Pull request closed without merging**
