### PR TITLE
Upgrade version

### PR DESCRIPTION
**Pull request by ynden**

### CODE REVIEW

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 04:44:29</summary>
    <details><summary>Locking successful</summary>
  Project digger-tests/digger-demo-opa#prod has been locked by PR #2
</details>

<details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_ will be created
  + resource "null_resource" "test_" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

</details>

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 05:00:30</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 19:10:20</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 19:13:30</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 19:17:31</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 19:44:05</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 19:52:39</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by ynden** [comment]
digger apply

**Comment by ynden** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 20:02:20</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 20:02:34</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 20:21:10</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_ will be created
  + resource "null_resource" "test_" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 20:21:14</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_ will be created
  + resource "null_resource" "test_" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test_: Creating...
null_resource.test_: Creation complete after 0s [id=6597768192947480810]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 20:25:37</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_ will be created
  + resource "null_resource" "test_" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test_: Creating...
null_resource.test_: Creation complete after 0s [id=8545665099507755146]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 20:25:38</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test_ will be created
  + resource "null_resource" "test_" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 20:37:34</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 20:37:35</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by ynden** [comment]
digger plan

**Comment by ynden** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 20:40:19</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-06 20:40:27</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by motatoes** [comment]
digger unlock

**Pull request closed without merging**
