### PR TITLE
 Testing OIDC test cases

### PR DESCRIPTION
**Pull request by Akritic**

### CODE REVIEW

**Comment by motatoes** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-08 07:04:01</summary>
  <details><summary>Policy violation</summary>
  User motatoes is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-08 07:08:25</summary>
  <details><summary>Locking failed</summary>
  Project digger-tests/digger-demo-opa#prod locked by another PR #2(failed to acquire lock prod). The locking plan must be applied or discarded before future plans can execute
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 01:24:57</summary>
  <details><summary>Locking failed</summary>
  Project digger-tests/digger-demo-opa#prod locked by another PR #2(failed to acquire lock prod). The locking plan must be applied or discarded before future plans can execute
</details>
</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 01:28:35</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 01:33:15</summary>
  <details><summary>Locking failed</summary>
  Project digger-tests/digger-demo-opa#prod locked by another PR #2(failed to acquire lock prod). The locking plan must be applied or discarded before future plans can execute
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 07:12:35</summary>
  <details><summary>Policy violation</summary>
  User motatoes is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Pull request closed without merging**
