### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by Akritic**

### CODE REVIEW

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 21:50:28</summary>
    <details><summary>Locking successful</summary>
  Project digger-tests/digger-demo-opa#prod has been locked by PR #5
</details>

<details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 21:58:29</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 22:30:01</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 22:30:28</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 22:34:09</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=3849609594620745505]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 22:36:38</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 22:36:57</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=7194872376182026133]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 22:39:45</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=8444715847455363854]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 22:40:22</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 22:42:54</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 22:44:01</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=1225601672258765751]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-09 22:46:41</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Comment by motatoes** [comment]
digger plan

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-07-10 06:21:43</summary>
  <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>
</details>

**Pull request closed without merging**
