### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by Akritic**

### CODE REVIEW

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-04 04:00:36 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-04 04:08:01 (UTC)</summary>
      <details><summary>Locking successful</summary>
  Project digger-tests/digger-demo-opa#prod has been locked by PR #11
</details>

<details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>


<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-04 04:09:34 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-04 04:11:21 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=787812544411443356]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-04 04:13:24 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-04 04:13:41 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=717976221698548321]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-04 04:16:15 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger apply. Check your policies
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-04 04:16:31 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User Akritic is not allowed to perform action: digger plan. Check your policies
</details>
</details>

**Comment by Akritic** [comment]
digger plan

**Comment by Akritic** [comment]
digger apply

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-04 04:18:24 (UTC)</summary>
  <details><summary>Apply for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.
null_resource.test1: Creating...
null_resource.test1: Creation complete after 0s [id=1344879970735472479]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

  ```
</details>
</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-04 04:18:43 (UTC)</summary>
    <details><summary>Plan for <b>digger-tests/digger-demo-opa#prod</b></summary>
  
```terraform
Terraform will perform the following actions:

  # null_resource.test1 will be created
  + resource "null_resource" "test1" {
      + id = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

─────────────────────────────────────────────────────────────────────────────
  ```
</details>

<details><summary>Terraform plan validation check (prod)</summary>
  Terraform plan validation checks succeeded :white_check_mark:
</details>

</details>

**Comment by motatoes** [comment]
<details><summary>Digger run report at 2023-08-13 14:32:41 (UTC)</summary>
  <details><summary>Policy violation</summary>
  User ynden is not allowed to perform action: digger unlock. Check your policies
</details>
</details>

**Pull request closed without merging**
